apiVersion: v1
kind: Service
metadata:
    name: weather-service
    labels:
        name: weather-service
spec:
    type: LoadBalancer
    selector:
        matchLabels:
            name: weather-pod
    ports:
        - name: http
          port: 0
          targetPort: weather-http